### System Health
GET http://127.0.0.1:8000/health

### Register Joey
POST http://127.0.0.1:8000/dog
Content-Type: application/json

{
    "name": "Joey",
    "breed": "Poodle",
    "is_favorite": true,
    "chip_number": "123-ABC"
}

### Search for Poodles
GET http://127.0.0.1:8000/dog?search=Poodle

### Log Weight (Success)
POST http://127.0.0.1:8000/weight
Content-Type: application/json

{
    "weight_kg": 7.5
}

### Log Weight (Fail - Validation)
POST http://127.0.0.1:8000/weight
Content-Type: application/json

{
    "weight_kg": -10
}
