### System Health Check
GET http://127.0.0.1:8000/health

### Register a New Dog (Joey)
POST http://127.0.0.1:8000/dog
Content-Type: application/json

{
  "name": "Joey",
  "breed": "Poodle",
  "chip_number": "123456789",
  "emergency_vet_name": "Dr. Bark",
  "emergency_vet_phone": "050-1234567"
}

### List All Registered Dogs
GET http://127.0.0.1:8000/dog

### Get Proactive Daily Tasks
GET http://127.0.0.1:8000/tasks/today
