[project]
name = "paw-health-api"
version = "0.1.0"
description = "EX3 Full-Stack Microservices Project"
dependencies = [
    "fastapi[all]",
    "sqlmodel",
    "pydantic-settings",
    "passlib[bcrypt]",
    "pyjwt",
    "pydantic-ai",
    "httpx",
    "anyio",
    "tenacity",
    "redis",
    "arq",
    "streamlit",
    "pandas"
]
